# Generated by Django 5.0.7 on 2024-09-05 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_product_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('transaction_no', models.CharField(max_length=100)),
                ('order_no', models.IntegerField()),
                ('bill_no', models.CharField(max_length=100, unique=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('minimum_stock_level', models.IntegerField(default=0)),
                ('maximum_stock_level', models.IntegerField(default=50)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_restock', models.BooleanField(default=False)),
                ('warehouse_location', models.CharField(default='', max_length=100)),
                ('aisle', models.CharField(default='', max_length=100)),
                ('shelf', models.CharField(default='', max_length=100)),
                ('bin', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stock')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.transactiontype'),
        ),
    ]
