# Generated by Django 5.0.7 on 2024-09-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_transaction_total_amount_alter_stock_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='updated_data',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-14'),
            preserve_default=False,
        ),
    ]
