# Generated by Django 5.0.7 on 2024-09-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_updated_data_stock_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='minimum_stock_level',
            field=models.IntegerField(default=10),
        ),
    ]
