# Generated by Django 5.0.7 on 2024-10-23 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_transaction_supplier'),
        ('products', '0005_alter_product_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.supplier'),
        ),
    ]
