# Generated by Django 5.0.7 on 2024-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
    ]
